#pragma once

#include "stdafx.h"

enum class Token
{
	TOKEN_TYPE_END_OF_STREAM			= 0,
	TOKEN_TYPE_INT						= 1,
	TOKEN_TYPE_FLOAT					= 2,

	//±£Áô×Ö
	TOKEN_TYPE_IDENT					= 3,
	TOKEN_TYPE_RSRVD_VAR				= 4,
	TOKEN_TYPE_RSRVD_TRUE				= 5,
	TOKEN_TYPE_RSRVD_FALSE				= 6,
	TOKEN_TYPE_RSRVD_IF					= 7,
	TOKEN_TYPE_RSRVD_ELSE				= 8,
	TOKEN_TYPE_RSRVD_BREAK				= 9,
	TOKEN_TYPE_RSRVD_CONTINUE			= 10,
	TOKEN_TYPE_RSRVD_FOR				= 11,
	TOKEN_TYPE_RSRVD_WHILE				= 12,
	TOKEN_TYPE_RSRVD_FUNC				= 13,
	TOKEN_TYPE_RSRVD_RETURN				= 14,

	//·Ö¸ô·û
	TOKEN_TYPE_DELIM_COMMA				= 15,
	TOKEN_TYPE_DELIM_OPEN_PAREN			= 16,
	TOKEN_TYPE_DELIM_CLOSE_PAREN		= 17,
	TOKEN_TYPE_DELIM_OPEN_BRACE			= 18,
	TOKEN_TYPE_DELIM_CLOSE_BRACE		= 19,
	TOKEN_TYPE_DELIM_OPEN_CURLY_BRACE	= 20,
	TOKEN_TYPE_DELIM_CLOSE_CURLY_BRACE	= 21,
	TOKEN_TYPE_DELIM_SEMICOLON			= 22,

	//ÔËËã·û
	TOKEN_TYPE_OP						= 23,

	//×Ö·û´®
	TOKEN_TYPE_STRING					= 24
};